package com.myspace.test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class teste implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public teste() {
    }




}